# Generated by Django 2.2.16 on 2021-12-14 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20211124_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='title',
            field=models.CharField(help_text='Выберите группу', max_length=200, verbose_name='Название'),
        ),
    ]
